CREATE DATABASE ONLINEPLATFORM;
\c ONLINEPLATFORM

CREATE TYPE user_role AS ENUM ('student', 'teacher', 'admin');
CREATE TYPE profile_avatar_type AS ENUM ('image', 'video', 'gif');

DROP TABLE users CASCADE;
CREATE TABLE IF NOT EXISTS users (
    ID SERIAL PRIMARY KEY,
    FULLNAME VARCHAR(64) DEFAULT 'student',
    TELEGRAM_USER_ID INT NOT NULL UNIQUE,
    CONTACT VARCHAR(32) NOT NULL UNIQUE,
    ROLE user_role DEFAULT 'student', 
    SIGNED_TIME TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP 
);

DROP TABLE courses CASCADE;
CREATE TABLE IF NOT EXISTS courses (
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL REFERENCES users(id),
    THUMBNAIL_URL VARCHAR(256) NOT NULL,
    TITLE VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR,
    PRICE FLOAT
);

DROP TABLE course_themes CASCADE;
CREATE TABLE IF NOT EXISTS course_themes (
    ID SERIAL PRIMARY KEY,
    COURSE_ID INT NOT NULL REFERENCES courses(id),
    TITLE VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(256)
);

DROP TABLE course_videos CASCADE;
CREATE TABLE IF NOT EXISTS course_videos (
    ID SERIAL PRIMARY KEY,
    GOOGLE_DRIVE_VIDEO_ID VARCHAR,
    THEME_ID INT NOT NULL REFERENCES course_themes(id),
    TITLE VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR,
    UPLOADED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE otp CASCADE;
CREATE TABLE IF NOT EXISTS otp (
    ID SERIAL PRIMARY KEY,
    telegram_user_id INT,
    code INT NOT NULL,
    sended_time TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE user_profile_avatar CASCADE;
CREATE TABLE IF NOT EXISTS user_profile_avatar (
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL REFERENCES users(ID),
    TYPE profile_avatar_type DEFAULT 'image',
    GOOGLE_DRIVE_PICTURE_URL VARCHAR(256),
    UPLOADED_TIME TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE users_queue CASCADE;
CREATE TABLE IF NOT EXISTS users_queue (
    ID SERIAL PRIMARY KEY,
    FULLNAME VARCHAR(64),
    TELEGRAM_USER_ID INT NOT NULL UNIQUE,
    CONTACT VARCHAR(32) NOT NULL UNIQUE,
    ROLE user_role DEFAULT 'student'
);